### ISSUE TITLE
Arbitrary resolution for torch models

### ISSUE THREAD

**Issue by DenShlk** [eps696/stylegan2ada#2] opened 2021-03-19 20:44 UTC
Hi! 
I think it is more likely that I did something wrong, but I can't generate anything with a non-native resolution.
I made a small research and found that legacy.py is used for loading models and resolution change is applied only for models converted from tensorflow.

Anyway, repo is great, thanks for your work!

**Comment by eps696** [comment] 2021-03-20 10:19
that's a problem indeed, occasionally got it myself just yesterday - the custom network (with all the tricks) is loaded only for old tf-based models, but not for newly trained on pytorch (i missed that point, cause didn't use it myself). 
the fix is on the way, stay tuned. 
[thanks]

**Comment by eps696** [comment] 2021-03-20 21:27
@DenShlk should be fixed now

**Comment by DenShlk** [comment] 2021-03-20 22:52
Now I'm getting this error:
```
 C:\stylegan2ada>gen.bat snapshot-256-0000 512-512 200-20
 .. Gs custom .. snapshot-256-0000
Traceback (most recent call last):
  File "src/_genSGAN2.py", line 163, in <module>
    generate()
  File "src/_genSGAN2.py", line 85, in generate
    Gs = legacy.load_network_pkl(f, custom=custom, **Gs_kwargs)['G_ema'].to(device) # type: ignore
  File "C:\stylegan2ada\src\legacy.py", line 44, in load_network_pkl
    G_ema = custom_generator(data, **ex_kwargs)
  File "C:\stylegan2ada\src\legacy.py", line 144, in custom_generator
    misc.copy_params_and_buffers(data['G_ema'], G_out, require_all=False)
  File "C:\stylegan2ada\src\torch_utils\misc.py", line 160, in copy_params_and_buffers
    tensor.copy_(src_tensors[name].detach()).requires_grad_(tensor.requires_grad)
RuntimeError: The size of tensor a (512) must match the size of tensor b (256) at non-singleton dimension 0
```

P. S. I did not find any examples of upgrading model output resolution, so could you explain, how it actually works?

**Comment by eps696** [comment] 2021-03-23 18:51
i cannot reproduce it here. could you send me one of your models for testing? (the earliest snapshot, just to check shapes).

the model itself is not upgraded (we don't have extra weights for that). it's the convolutional layers that are resized (cropped or padded) during inference instead. have a look at `fix_size` function in `stylegan2_multi.py` and `utilgan.py` to get a clue.

**Comment by DenShlk** [comment] 2021-03-23 19:23
https://drive.google.com/file/d/1OHuKMJFH0b85ql2vMrD9bWYFjAiwvXAE/view?usp=sharing

This model is generated with the last version of this repository. It is 256x256.
As you see above I use `gen.bat <name> 512-512 200-20` command.

**Comment by eps696** [comment] 2021-03-23 20:44
try now, should be ok.

[it appeared, sg2 authors did not make `fmap_base` value available for network reconstruction, despite it's important and varies with config and resolution]

**Comment by DenShlk** [comment] 2021-03-25 06:17
Great thanks! it works perfectly.

**Closed as completed** 2021-03-25 08:14 UTC
